version: '3'
services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: subjects-api
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/courses
    ports:
      - '8000:8000'
    restart: unless-stopped