version: '3.3'

volumes:
  static_django_analytics:
  tests_data:

services:
  client:
    build:
      context: ../
      dockerfile: client/Dockerfile
    volumes:
      - static_django_analytics:/client/build/

  api:
    build:
      context: ../subjects
      dockerfile: docker/dev/Dockerfile
    env_file:
      - ./env/.env.subjects
    command: ./cmd.subjects.sh
    volumes:
      - ../dbs/subjects_db.sqlite3:/app/db.sqlite3
      - ./startscripts/cmd.subjects.sh:/app/cmd.subjects.sh
      - static_django_analytics:/app/static_django_analytics/
    restart: unless-stopped
    depends_on:
      - client

  users:
    build: ../users/
    env_file:
      - ./env/.env.users
    command: ./cmd.users.sh
    volumes:
      - ../dbs/users_db.sqlite3:/app/db.sqlite3
      - ./startscripts/cmd.users.sh:/app/cmd.users.sh
      - static_django_analytics:/app/static_django_analytics/
    depends_on:
      - client
    restart: unless-stopped

  tests:
    build: ../tests/
    env_file:
      - ./env/.env.tests
    command: ./cmd.tests.sh
    volumes:
      - ../dbs/tests_db.sqlite3:/app/db.sqlite3
      - ./startscripts/cmd.tests.sh:/app/cmd.tests.sh
      - tests_data:/app/tests
      - static_django_analytics:/app/static_django_analytics/
    depends_on:
      - client
    restart: unless-stopped

  analytics:
    build: ../analytics/
    env_file:
      - ./env/.env.analytics
    command: ./cmd.analytics.sh
    volumes:
      - ../dbs/analytics_db.sqlite3:/app/db.sqlite3
      - ./startscripts/cmd.analytics.sh:/app/cmd.analytics.sh
      - tests_data:/app/tests
      - static_django_analytics:/app/static_django_analytics/
    depends_on:
      - tests
    restart: unless-stopped



  gateway:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_django_analytics:/usr/share/nginx/html/
    restart: unless-stopped
    depends_on:
      - client
      - users
      - tests
      - api
      - analytics
