name: Main devops_demo workflow

on:
  push:
    branches:
      - DEV
jobs:
  build_and_push_front_to_docker_hub:
    name: Push Docker frontend image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'DEV'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to Docker 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./
          file: client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:DEV

  build_and_push_users_to_docker_hub:
    name: Push Docker Users image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'DEV'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to Docker 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./users
          file: users/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-users:DEV

  build_and_push_tests_to_docker_hub:
    name: Push Docker tests image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'DEV'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to Docker 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          file: tests/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-tests:DEV

  build_and_push_subjects_to_docker_hub:
    name: Push Docker subjects image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'DEV'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to Docker 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./subjects
          file: docker/dev/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-subjects:DEV