name: DEV workflow

on:
  push:
    branches:
      - DEV
jobs:
  deploy:
    name: Деплой на сервер
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Executing remote ssh commands to stop docker and clean up
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cp -r DEV/compose/env ./env
          rm -rf DEV
          mkdir -p DEV/compose
          mv ./env DEV/compose
#